import re


TONE_ID = ['flat', 'rise', 'fall', 'inquire', 'break', 'heavy']
TONE = {
    TONE_ID[0]: '',
    TONE_ID[1]: 's',
    TONE_ID[2]: 'f',
    TONE_ID[3]: 'r',
    TONE_ID[4]: 'x',
    TONE_ID[5]: 'j',
}
NUCLEI = {
    'a': {
        TONE_ID[0]: 'a',
        TONE_ID[1]: 'á',
        TONE_ID[2]: 'à',
        TONE_ID[3]: 'ả',
        TONE_ID[4]: 'ã',
        TONE_ID[5]: 'ạ',
    },
    'ă': {
        TONE_ID[0]: 'ă',
        TONE_ID[1]: 'ắ',
        TONE_ID[2]: 'ằ',
        TONE_ID[3]: 'ẳ',
        TONE_ID[4]: 'ẵ',
        TONE_ID[5]: 'ặ',
    },
    'â': {
        TONE_ID[0]: 'â',
        TONE_ID[1]: 'ấ',
        TONE_ID[2]: 'ầ',
        TONE_ID[3]: 'ẩ',
        TONE_ID[4]: 'ẫ',
        TONE_ID[5]: 'ậ',
    },
    'e': {
        TONE_ID[0]: 'e',
        TONE_ID[1]: 'é',
        TONE_ID[2]: 'è',
        TONE_ID[3]: 'ẻ',
        TONE_ID[4]: 'ẽ',
        TONE_ID[5]: 'ẹ',
    },
    'ê': {
        TONE_ID[0]: 'ê',
        TONE_ID[1]: 'ế',
        TONE_ID[2]: 'ề',
        TONE_ID[3]: 'ể',
        TONE_ID[4]: 'ễ',
        TONE_ID[5]: 'ệ',
    },
    'i': {
        TONE_ID[0]: 'i',
        TONE_ID[1]: 'í',
        TONE_ID[2]: 'ì',
        TONE_ID[3]: 'ỉ',
        TONE_ID[4]: 'ĩ',
        TONE_ID[5]: 'ị',
    },
    'o': {
        TONE_ID[0]: 'o',
        TONE_ID[1]: 'ó',
        TONE_ID[2]: 'ò',
        TONE_ID[3]: 'ỏ',
        TONE_ID[4]: 'õ',
        TONE_ID[5]: 'ọ',
    },
    'ô': {
        TONE_ID[0]: 'ô',
        TONE_ID[1]: 'ố',
        TONE_ID[2]: 'ồ',
        TONE_ID[3]: 'ổ',
        TONE_ID[4]: 'ỗ',
        TONE_ID[5]: 'ộ',
    },
    'ơ': {
        TONE_ID[0]: 'ơ',
        TONE_ID[1]: 'ớ',
        TONE_ID[2]: 'ờ',
        TONE_ID[3]: 'ở',
        TONE_ID[4]: 'ỡ',
        TONE_ID[5]: 'ợ',
    },
    'u': {
        TONE_ID[0]: 'u',
        TONE_ID[1]: 'ú',
        TONE_ID[2]: 'ù',
        TONE_ID[3]: 'ủ',
        TONE_ID[4]: 'ũ',
        TONE_ID[5]: 'ụ',
    },
    'ư': {
        TONE_ID[0]: 'ư',
        TONE_ID[1]: 'ứ',
        TONE_ID[2]: 'ừ',
        TONE_ID[3]: 'ử',
        TONE_ID[4]: 'ữ',
        TONE_ID[5]: 'ự',
    },
    'y': {
        TONE_ID[0]: 'y',
        TONE_ID[1]: 'ý',
        TONE_ID[2]: 'ỳ',
        TONE_ID[3]: 'ỷ',
        TONE_ID[4]: 'ỹ',
        TONE_ID[5]: 'ỵ',
    },
    'iê': {
        TONE_ID[0]: 'iê',
        TONE_ID[1]: 'iế',
        TONE_ID[2]: 'iề',
        TONE_ID[3]: 'iể',
        TONE_ID[4]: 'iễ',
        TONE_ID[5]: 'iệ',
    },
    'oa': {
        TONE_ID[0]: 'oa',
        TONE_ID[1]: 'óa',
        TONE_ID[2]: 'òa',
        TONE_ID[3]: 'ỏa',
        TONE_ID[4]: 'oã',
        TONE_ID[5]: 'ọa',
    },
    'oă': {
        TONE_ID[0]: 'oă',
        TONE_ID[1]: 'oắ',
        TONE_ID[2]: 'oằ',
        TONE_ID[3]: 'oẳ',
        TONE_ID[4]: 'oẵ',
        TONE_ID[5]: 'oặ',
    },
    'oe': {
        TONE_ID[0]: 'oe',
        TONE_ID[1]: 'óe',
        TONE_ID[2]: 'òe',
        TONE_ID[3]: 'ỏe',
        TONE_ID[4]: 'õe',
        TONE_ID[5]: 'ọe',
    },
    'oo': {
        TONE_ID[0]: 'oo',
        TONE_ID[1]: 'óo',
        TONE_ID[2]: 'òo',
        TONE_ID[3]: 'ỏo',
        TONE_ID[4]: 'õo',
        TONE_ID[5]: 'ọo',
    },
    'uâ': {
        TONE_ID[0]: 'uâ',
        TONE_ID[1]: 'uấ',
        TONE_ID[2]: 'uầ',
        TONE_ID[3]: 'uẩ',
        TONE_ID[4]: 'uẫ',
        TONE_ID[5]: 'uậ',
    },
    'uê': {
        TONE_ID[0]: 'uê',
        TONE_ID[1]: 'uế',
        TONE_ID[2]: 'uề',
        TONE_ID[3]: 'uể',
        TONE_ID[4]: 'uễ',
        TONE_ID[5]: 'uệ',
    },
    'uô': {
        TONE_ID[0]: 'uô',
        TONE_ID[1]: 'uố',
        TONE_ID[2]: 'uồ',
        TONE_ID[3]: 'uổ',
        TONE_ID[4]: 'uỗ',
        TONE_ID[5]: 'uộ',
    },
    'uơ': {
        TONE_ID[0]: 'uơ',
        TONE_ID[1]: 'uớ',
        TONE_ID[2]: 'uờ',
        TONE_ID[3]: 'uở',
        TONE_ID[4]: 'uỡ',
        TONE_ID[5]: 'uợ',
    },
    'uy': {
        TONE_ID[0]: 'uy',
        TONE_ID[1]: 'uý',
        TONE_ID[2]: 'uỳ',
        TONE_ID[3]: 'uỷ',
        TONE_ID[4]: 'uỹ',
        TONE_ID[5]: 'uỵ',
    },
    'ươ': {
        TONE_ID[0]: 'ươ',
        TONE_ID[1]: 'ướ',
        TONE_ID[2]: 'ườ',
        TONE_ID[3]: 'ưở',
        TONE_ID[4]: 'ưỡ',
        TONE_ID[5]: 'ượ',
    },
    'uyê': {
        TONE_ID[0]: 'uyê',
        TONE_ID[1]: 'uyế',
        TONE_ID[2]: 'uyề',
        TONE_ID[3]: 'uyể',
        TONE_ID[4]: 'uyễ',
        TONE_ID[5]: 'uyệ',
    },
    'yê': {
        TONE_ID[0]: 'yê',
        TONE_ID[1]: 'yế',
        TONE_ID[2]: 'yề',
        TONE_ID[3]: 'yể',
        TONE_ID[4]: 'yễ',
        TONE_ID[5]: 'yệ',
    },
}

